const menuHndlr = (aselolew) => {
    return `╭────✎「 Anonymous 」
│• ${aselolew}confess
│• ${aselolew}menfess
│• ${aselolew}start
│• ${aselolew}next
│• ${aselolew}leave
╰─────────❍
╭────✎「 Anime 」
│• ${aselolew}anime
│• ${aselolew}aniplanet
│• ${aselolew}character
│• ${aselolew}kiryu
│• ${aselolew}klikmanga
│• ${aselolew}kissmanga
│• ${aselolew}kusonime
│• ${aselolew}manga
╰─────────❍
╭────✎「 Convert 」
│• ${aselolew}bass
│• ${aselolew}blown
│• ${aselolew}bitly
│• ${aselolew}clppw
│• ${aselolew}cuttly
│• ${aselolew}deep
│• ${aselolew}dbinary
│• ${aselolew}ebinary
│• ${aselolew}errape
│• ${aselolew}expandurl
│• ${aselolew}fast
│• ${aselolew}fat
│• ${aselolew}halah
│• ${aselolew}hilih
│• ${aselolew}huluh
│• ${aselolew}heleh
│• ${aselolew}holoh
│• ${aselolew}nightcore
│• ${aselolew}readqr
│• ${aselolew}reverse
│• ${aselolew}robot
│• ${aselolew}slow
│• ${aselolew}smooth
│• ${aselolew}styletext
│• ${aselolew}toaudio
│• ${aselolew}togif
│• ${aselolew}toimg
│• ${aselolew}tomp3
│• ${aselolew}tomp4
│• ${aselolew}totext
│• ${aselolew}tourl
│• ${aselolew}toqr
│• ${aselolew}tovn
│• ${aselolew}tts
│• ${aselolew}tupai
│• ${aselolew}tinyurl
╰─────────❍
╭────✎「 Download 」
│• ${aselolew}fb
│• ${aselolew}ig
│• ${aselolew}igstory
│• ${aselolew}imdb
│• ${aselolew}mediafire
│• ${aselolew}pinterestdl
│• ${aselolew}spotify
│• ${aselolew}tt
│• ${aselolew}ttmp3
│• ${aselolew}twitter
│• ${aselolew}ytmp3
│• ${aselolew}ytmp4
╰─────────❍
╭────✎「 Games 」
│• ${aselolew}addbalance
│• ${aselolew}adventure
│• ${aselolew}asahotak
│• ${aselolew}caklontong
│• ${aselolew}claim
│• ${aselolew}daily
│• ${aselolew}dare
│• ${aselolew}delttt
│• ${aselolew}family100
│• ${aselolew}Jadian
│• ${aselolew}Jodohku
│• ${aselolew}math
│• ${aselolew}siapakahaku
│• ${aselolew}suitpvp
│• ${aselolew}tebak
│• ${aselolew}tebakbendera
│• ${aselolew}tf
│• ${aselolew}tictactoe
│• ${aselolew}truth
│• ${aselolew}inv
│• ${aselolew}judi
│• ${aselolew}mulung
│• ${aselolew}slot
│• ${aselolew}weekly
╰─────────❍
╭────✎「 Group 」
│• ${aselolew}add
│• ${aselolew}demote
│• ${aselolew}group
│• ${aselolew}hidetag
│• ${aselolew}kick
│• ${aselolew}linkgroup
│• ${aselolew}promote
│• ${aselolew}setppgc
│• ${aselolew}setname
│• ${aselolew}setdesc
│• ${aselolew}tagall
╰─────────❍
╭────✎「 Kerang Ajaib 」
│• ${aselolew}apakah
│• ${aselolew}bisakah
│• ${aselolew}cekcantik
│• ${aselolew}cekganteng
│• ${aselolew}kapan
│• ${aselolew}kerang
│• ${aselolew}rate
╰─────────❍
╭────✎「 Owner 」
│• ${aselolew}addsewa
│• ${aselolew}antilink
│• ${aselolew}block
│• ${aselolew}ceksewa
│• ${aselolew}setexif
│• ${aselolew}setppbot
│• ${aselolew}unblock
╰─────────❍
╭────✎「 Search 」
│• ${aselolew}beasiswa
│• ${aselolew}chord
│• ${aselolew}cerpen
│• ${aselolew}faktaunik
│• ${aselolew}film
│• ${aselolew}gcwa
│• ${aselolew}gimage
│• ${aselolew}google
│• ${aselolew}githubstalk
│• ${aselolew}happymod
│• ${aselolew}hoax
│• ${aselolew}igstalk
│• ${aselolew}jalantikus
│• ${aselolew}jadwalbola
│• ${aselolew}jadwaltv
│• ${aselolew}joox
│• ${aselolew}katabijak
│• ${aselolew}katabucin
│• ${aselolew}kompasnews
│• ${aselolew}lirik
│• ${aselolew}lk21
│• ${aselolew}mangatoons
│• ${aselolew}noveltoons
│• ${aselolew}play
│• ${aselolew}pantun
│• ${aselolew}puisi
│• ${aselolew}quote
│• ${aselolew}quotes
│• ${aselolew}searchbijak
│• ${aselolew}sfilesearch
│• ${aselolew}translate
│• ${aselolew}twitterstalk
│• ${aselolew}unsplash
│• ${aselolew}wallpaper
│• ${aselolew}webtoons
│• ${aselolew}whatmusic
│• ${aselolew}wiki
╰─────────❍
╭────✎「 Premium 」
│• ${aselolew}beliyt
│• ${aselolew}belisp
│• ${aselolew}cekprem
│• ${aselolew}react
│• ${aselolew}mute
│• ${aselolew}unmute
│• ${aselolew}join
│• ${aselolew}outgc
╰─────────❍
╭────✎「 Random Image 」
│• ${aselolew}elf
│• ${aselolew}gawrgura
│• ${aselolew}loli
│• ${aselolew}meme
│• ${aselolew}memeindo
│• ${aselolew}neko
│• ${aselolew}nsfwloli
│• ${aselolew}nsfwneko
│• ${aselolew}nsfwwaifu
│• ${aselolew}ppcp
│• ${aselolew}randcry
│• ${aselolew}randkiss
│• ${aselolew}randwp
│• ${aselolew}waifu
╰─────────❍
╭────✎「 Sticker 」
│• ${aselolew}amongus
│• ${aselolew}attp
│• ${aselolew}bucinstick
│• ${aselolew}dogestick
│• ${aselolew}emojimix
│• ${aselolew}smeme
│• ${aselolew}stiker
│• ${aselolew}stikerwm
│• ${aselolew}take
│• ${aselolew}ttp
╰─────────❍
╭────✎「 Maker 」
│• ${aselolew}blur
│• ${aselolew}beautiful
│• ${aselolew}burningfire
│• ${aselolew}carbon
│• ${aselolew}facepalm
│• ${aselolew}flip
│• ${aselolew}fisheye
│• ${aselolew}galaxy
│• ${aselolew}greenbush
│• ${aselolew}hartatahta
│• ${aselolew}hitler
│• ${aselolew}hologram
│• ${aselolew}invert
│• ${aselolew}jokeoverhead
│• ${aselolew}logofps
│• ${aselolew}logogaming
│• ${aselolew}logoanonym
│• ${aselolew}logoneon
│• ${aselolew}logotiktok
│• ${aselolew}multicolor3d
│• ${aselolew}nulis
│• ${aselolew}ohno
│• ${aselolew}opinion
│• ${aselolew}pencils
│• ${aselolew}phub
│• ${aselolew}pixelate
│• ${aselolew}pcup
│• ${aselolew}pcup2
│• ${aselolew}psmoke
│• ${aselolew}pshadow
│• ${aselolew}rip
│• ${aselolew}rainbow
│• ${aselolew}removebg
│• ${aselolew}resize
│• ${aselolew}rotate
│• ${aselolew}roundimg
│• ${aselolew}shit
│• ${aselolew}ssweb
│• ${aselolew}trash
│• ${aselolew}triggered
│• ${aselolew}watercolor
│• ${aselolew}wetglass
│• ${aselolew}wasted
│• ${aselolew}wanted
│• ${aselolew}ytcomment
│• ${aselolew}yugioh
│• ${aselolew}candy
│• ${aselolew}christmas
│• ${aselolew}3dchristmas
│• ${aselolew}sparklechristmas
│• ${aselolew}holographic
│• ${aselolew}deepsea
│• ${aselolew}scifi
│• ${aselolew}rainbow
│• ${aselolew}waterpipe
│• ${aselolew}spooky
│• ${aselolew}karbon
│• ${aselolew}neonlight2
│• ${aselolew}pencil
│• ${aselolew}circuit
│• ${aselolew}discovery
│• ${aselolew}metalic
│• ${aselolew}fiction
│• ${aselolew}demon
│• ${aselolew}3dbox
│• ${aselolew}transformer
│• ${aselolew}berry
│• ${aselolew}thunder
│• ${aselolew}magma
│• ${aselolew}3dstone
│• ${aselolew}greenneon
│• ${aselolew}neonlight
│• ${aselolew}glitch
│• ${aselolew}harrypotter
│• ${aselolew}brokenglass
│• ${aselolew}papercut
│• ${aselolew}lion2
│• ${aselolew}watercolor
│• ${aselolew}neondevil
│• ${aselolew}underwater
│• ${aselolew}graffitibike
│• ${aselolew}3davengers
│• ${aselolew}snow
│• ${aselolew}cloud
│• ${aselolew}honey
│• ${aselolew}ice
│• ${aselolew}fruitjuice
│• ${aselolew}bicuit
│• ${aselolew}wood
│• ${aselolew}whitebear
│• ${aselolew}chocolate
│• ${aselolew}strawberry
│• ${aselolew}matrix
│• ${aselolew}blood
│• ${aselolew}dropwater
│• ${aselolew}toxic
│• ${aselolew}lava
│• ${aselolew}rock
│• ${aselolew}bloodglas
│• ${aselolew}hallowen
│• ${aselolew}darkgold
│• ${aselolew}joker
│• ${aselolew}wicker
│• ${aselolew}firework
│• ${aselolew}skeleton
│• ${aselolew}blackpink
│• ${aselolew}sand
│• ${aselolew}glue
│• ${aselolew}1917
│• ${aselolew}leaves
╰─────────❍`
}

module.exports = {menuHndlr}